#' @importFrom utils getFromNamespace
prepare_KEGG <- getFromNamespace("prepare_KEGG","clusterProfiler")
get_GO_data <- getFromNamespace("get_GO_data","clusterProfiler")
getGeneSet <- getFromNamespace("getGeneSet","DOSE")
prepare_KEGG <- getFromNamespace("prepare_KEGG","clusterProfiler")
get_organism <- getFromNamespace("get_organism", "DOSE")
gson_cpd <- getFromNamespace("gson_cpd","clusterProfiler")
organismMapper <- getFromNamespace("organismMapper","clusterProfiler")
get_data_from_KEGG_db <- getFromNamespace("get_data_from_KEGG_db","clusterProfiler")
build_Anno <- getFromNamespace("build_Anno","clusterProfiler")
is.sorted <- getFromNamespace("is.sorted", "DOSE")
